# Generated by Django 5.1.6 on 2026-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='incident_type',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='next_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='notification_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('EMERGENCY', 'Emergency')], db_index=True, default='NORMAL', max_length=12),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='reporter_roll_no',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='reporter_room_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
