# Generated by Django 5.1.6 on 2026-04-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pushdevicetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appnotification',
            name='incident_type',
        ),
        migrations.RemoveField(
            model_name='appnotification',
            name='next_steps',
        ),
        migrations.RemoveField(
            model_name='appnotification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='appnotification',
            name='reporter_name',
        ),
        migrations.RemoveField(
            model_name='appnotification',
            name='reporter_roll_no',
        ),
        migrations.RemoveField(
            model_name='appnotification',
            name='reporter_room_no',
        ),
        migrations.DeleteModel(
            name='PushDeviceToken',
        ),
    ]
