# Generated by Django 5.1.6 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0003_laundryroomrange"),
    ]

    operations = [
        migrations.AddField(
            model_name="laundryroomrange",
            name="scheduled_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="laundryroomrange",
            name="day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                    ("SUN", "Sunday"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="laundryroomrange",
            options={"ordering": ["block_name", "scheduled_date", "day_of_week", "room_from"]},
        ),
    ]
