# Generated by Django 5.1.6 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0004_laundryroomrange_scheduled_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaundryHoliday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("holiday_date", models.DateField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["holiday_date"],
            },
        ),
    ]
