# Generated by Django 5.1.6 on 2026-03-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('roll_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('room_no', models.CharField(max_length=10)),
                ('points_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mess_allotment', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='hostels.hostelblock')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='hostels.room')),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
    ]
