# Generated by Django 5.1.6 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mess", "0003_seed_sample_menus"),
    ]

    operations = [
        migrations.AddField(
            model_name="menupolloption",
            name="poll_type",
            field=models.CharField(
                choices=[("ADD", "Add Request"), ("REMOVE", "Dislike Existing")],
                default="ADD",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menupolloption",
            unique_together={("month", "item_name", "poll_type")},
        ),
    ]
