# Generated by Django 5.1.6 on 2026-03-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
        ('mess', '0004_poll_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('meal_types', models.CharField(help_text='Comma separated values: veg, nonveg, special, foodpark', max_length=120)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterers', to='hostels.hostelblock')),
            ],
            options={
                'ordering': ['block__block_name', 'name'],
                'unique_together': {('name', 'block')},
            },
        ),
    ]
