# Generated by Django 5.1.6 on 2026-03-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0005_caterer'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='meal_time',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACKS', 'Snacks'), ('DINNER', 'Dinner')], default='BREAKFAST', max_length=12),
        ),
        migrations.AddField(
            model_name='feedback',
            name='week_day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], default='MON', max_length=3),
        ),
    ]
