# Generated by Django 5.1.6 on 2026-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0011_caterer_capacity_and_menu_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMonthlyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('kind', models.CharField(choices=[('FEEDBACK', 'Feedback Trends'), ('POLL', 'Poll Snapshot')], db_index=True, max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month', 'kind', '-archived_at'],
                'unique_together': {('month', 'kind')},
            },
        ),
    ]
