# Generated by Django 5.1.6 on 2026-03-27 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SUBMISSION', 'Submission'), ('COLLECTION', 'Collection')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaundrySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('holidays', models.JSONField(blank=True, default=list)),
                ('qr_token', models.CharField(default=uuid.uuid4, editable=False, max_length=100)),
                ('submission_status', models.BooleanField(default=False)),
                ('collection_status', models.BooleanField(default=False)),
                ('last_submission_at', models.DateTimeField(blank=True, null=True)),
                ('due_collection_by', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
