# Generated by Django 5.1.6 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_otpchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_mess_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARPENTRY", "Carpentry"),
                    ("PLUMBING", "Plumbing"),
                    ("AC", "AC"),
                    ("DRINKING_WATER", "Drinking Water"),
                    ("UTILITY_WATER", "Utility Water"),
                    ("DISCIPLINE", "Discipline"),
                    ("CIVIL_INFRA", "Civil/Infra"),
                    ("ELECTRICAL", "Electrical"),
                    ("GYM", "Gym"),
                    ("CLEANING", "Cleaning"),
                    ("SECURITY", "Security"),
                    ("LAUNDRY", "Laundry"),
                    ("MESS_ISSUES", "Mess Issues"),
                    ("MESS_MANAGEMENT", "Mess Management"),
                    ("HOSTEL_ADMIN", "Hostel Administration"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_country_code",
            field=models.CharField(default="+91", max_length=6),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STUDENT", "Student"),
                    ("WARDEN", "Warden"),
                    ("MESS_MANAGER", "Mess Manager"),
                    ("LAUNDRY_PERSON", "Laundry Person"),
                    ("SUPERVISOR", "Supervisor"),
                    ("DIRECTOR", "Director"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
