# Generated by Django 5.1.6 on 2026-03-28 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_signup_profile_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpchallenge',
            new_name='users_otpch_user_id_ba3a2c_idx',
            old_name='users_otpch_user_id_00f04a_idx',
        ),
    ]
