# Generated by Django 5.1.6 on 2026-04-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinecase',
            name='violation_code',
            field=models.CharField(choices=[('LATE_ENTRY_AT_NIGHT', 'Late entry to hostel at night (9:00 PM boys, 8:00 PM girls)'), ('AVOID_ATTENDANCE_OR_NIGHT_ABSENCE', 'Avoiding hostel attendance or not being present at night'), ('ENTERING_WITHOUT_ID_CARD', 'Entering campus or hostel gate without ID card'), ('MISUSE_OF_ID_CARD', 'Misuse of student ID card'), ('LATE_AFTER_OUTING', 'Late coming after outing'), ('ABSENT_WITHOUT_LEAVE', 'Absent without obtaining leave'), ('ROOM_SWAPPING_WITHOUT_PERMISSION', 'Room swapping without hostel authority information'), ('ALLOWING_NON_RESIDENT_INSIDE', 'Allowing day scholar/day boarder/non-VITian inside hostel'), ('UNAUTHORIZED_ENTRY_OTHER_BLOCKS', 'Unauthorized entry to other hostel blocks'), ('BIRTHDAY_OR_PARTY_DISRUPTION', 'Birthday celebration/party disturbing hostel tranquillity'), ('LOUD_MUSIC_OR_DISTURBANCE', 'Loud music/games/activities disturbing others'), ('UNALLOTTED_MESS_CONSUMPTION', 'Having food from non-allotted mess'), ('MISBEHAVING_WITH_AUTHORITY', 'Misbehaving with hostel authorities'), ('UNAUTHORIZED_ENTRY_HOSTEL_OFFICE', 'Entering hostel office without permission and taking confiscated items'), ('MISUSING_DRINKING_WATER', 'Misusing drinking water'), ('DAMAGING_VIT_PROPERTY', 'Damaging VIT property'), ('STEALING_VIT_PROPERTY', 'Stealing VIT property'), ('STEALING_INMATE_PROPERTY', 'Stealing hostel inmate property'), ('SMOKING', 'Smoking'), ('E_SMOKING', 'E-smoking (Prohibition of Electronic Cigarettes Act, 2019)'), ('E_CIGARETTE_TRADE', 'Sale/trading of e-cigarettes/vape'), ('DRUNKEN_ENTRY', 'Coming to hostel in drunken state'), ('ALCOHOL_POSSESSION_OR_INDUCING', 'Bringing/possessing/drinking liquor in hostel or inducing others'), ('ALCOHOL_NON_COOP_MEDICAL', 'Alcohol consumption and non-cooperation for medical check-up'), ('NARCOTIC_SUBSTANCE_USE_OR_SALE', 'Using/selling narcotic substances or inducing others'), ('FIGHT_MINOR_INJURY', 'Fighting/slander/quarrelling causing minor injury'), ('FIGHT_MAJOR_INJURY', 'Fighting/slander/quarrelling causing major injury'), ('HARASSMENT', 'Mental/physical/sexual harassment'), ('RAGGING', 'Ragging'), ('PLAYING_WITH_FIRE', 'Setting fire/playing with fire/bursting crackers'), ('MISUSING_FIRE_ALARM', 'Misusing/playing with fire alarm'), ('SOCIAL_MEDIA_DEFAMATION_INMATE', 'Defaming hostel inmates through social media'), ('SOCIAL_MEDIA_DEFAMATION_VIT', 'Defaming VIT through social media'), ('HACKING_OR_UNAUTHORIZED_ACCESS', 'Hacking/unauthorized device access for file/data changes'), ('FORGERY_OR_FINANCIAL_FRAUD', 'Forgery/gambling/fraud/multilevel marketing/financial fraud'), ('MOTOR_VEHICLE_IN_HOSTEL', 'Bringing motor vehicles to hostel area or using rental for outing'), ('ELECTRICAL_APPLIANCE_POSSESSION', 'Possession/usage of electrical appliances in hostel room'), ('FALSE_INFORMATION_IN_ENQUIRY', 'Giving false information during enquiry'), ('MULTIPLE_OFFICE_ORDERS', 'Getting office orders for more than three occasions'), ('SELLING_ITEMS_FOR_POCKET_MONEY', 'Selling items in hostel for pocket money')], max_length=80),
        ),
    ]
