name: hostel_cc_app
description: Hostel management Flutter client for all roles with Fluent Design UI.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  fluentui_system_icons: ^1.1.228
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0
  screen_brightness: ^2.1.2
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^33.1.45
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
