# Generated by Django 5.1.6 on 2026-03-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D1', 'D1'), ('D2', 'D2'), ('E', 'E')], db_index=True, max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostels.hostelblock')),
            ],
            options={
                'unique_together': {('block', 'room_no')},
            },
        ),
    ]
