# Generated by Django 5.1.6 on 2026-03-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mess', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_feedback', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='menupolloption',
            unique_together={('month', 'item_name')},
        ),
        migrations.AddField(
            model_name='menupollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mess.menupolloption'),
        ),
        migrations.AddField(
            model_name='menupollvote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='messchangerequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_change_requests', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='menupollvote',
            unique_together={('student', 'option')},
        ),
    ]
