# Generated by Django 5.1.6 on 2026-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0007_mess_type_menu_and_caterer_mapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caterer',
            options={'ordering': ['block__block_name', 'meal_types', 'name']},
        ),
        migrations.AlterModelOptions(
            name='messmenu',
            options={'ordering': ['mess_type', 'week_day']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='week_day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3),
        ),
    ]
