# Generated by Django 5.1.6 on 2026-03-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_author_from_student(apps, schema_editor):
    Complaint = apps.get_model("complaints", "Complaint")
    for complaint in Complaint.objects.select_related("student__user").all():
        student = complaint.student
        complaint.author_id = getattr(student, "user_id", None)
        complaint.save(update_fields=["author"])


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complaints", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="community_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="downvotes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="complaint",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="complaints/media/"),
        ),
        migrations.AddField(
            model_name="complaint",
            name="media_type",
            field=models.CharField(
                choices=[("TEXT", "Text"), ("IMAGE", "Image"), ("VIDEO", "Video")],
                default="TEXT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="upvotes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="category",
            field=models.CharField(
                choices=[
                    ("CARPENTRY", "Carpentry"),
                    ("PLUMBING", "Plumbing"),
                    ("AC", "AC"),
                    ("DRINKING_WATER", "Drinking Water"),
                    ("UTILITY_WATER", "Utility Water"),
                    ("DISCIPLINE", "Discipline"),
                    ("CIVIL_INFRA", "Civil/Infra"),
                    ("ELECTRICAL", "Electrical"),
                    ("GYM", "Gym"),
                    ("CLEANING", "Cleaning"),
                    ("SECURITY", "Security"),
                    ("LAUNDRY", "Laundry"),
                    ("MESS_ISSUES", "Mess Issues"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="students.student",
            ),
        ),
        migrations.RunPython(assign_author_from_student, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ComplaintVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.SmallIntegerField(choices=[(-1, "Downvote"), (1, "Upvote")])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complaint",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="complaints.complaint"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="complaint_votes", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("complaint", "user")},
            },
        ),
    ]
