# Generated by Django 5.1.6 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_community_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_PROGRESS", "In Progress"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
